# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: seojo <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/04 20:08:00 by seojo             #+#    #+#              #
#    Updated: 2022/11/04 20:08:32 by seojo            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

gcc -lreadline -L/Users/seojo/Desktop/readline/lib -I/Users/seojo/Desktop/readline/include
CFLAGS	=	-Wall -Wextra -Werror

